-- CREATE SEQUENCE IF NOT EXISTS primary_key_seq
--     START WITH 1
--     INCREMENT BY 1
--     NO MINVALUE
--     NO MAXVALUE
--     CACHE 1;


-- -- This script was generated by the ERD tool in pgAdmin 4.
-- -- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
-- BEGIN;


-- CREATE TABLE IF NOT EXISTS public.confirmations
-- (
--     created_at timestamp(6) without time zone NOT NULL,
--     created_by bigint NOT NULL,
--     id bigint NOT NULL,
--     updated_at timestamp(6) without time zone NOT NULL,
--     updated_by bigint NOT NULL,
--     user_id bigint NOT NULL,
--     key character varying(255) COLLATE pg_catalog."default",
--     reference_id character varying(255) COLLATE pg_catalog."default",
--     CONSTRAINT confirmations_pkey PRIMARY KEY (id),
--     CONSTRAINT confirmations_user_id_key UNIQUE (user_id)
-- );

-- CREATE TABLE IF NOT EXISTS public.credentials
-- (
--     created_at timestamp(6) without time zone NOT NULL,
--     created_by bigint NOT NULL,
--     id bigint NOT NULL,
--     updated_at timestamp(6) without time zone NOT NULL,
--     updated_by bigint NOT NULL,
--     user_id bigint NOT NULL,
--     password character varying(255) COLLATE pg_catalog."default",
--     reference_id character varying(255) COLLATE pg_catalog."default",
--     CONSTRAINT credentials_pkey PRIMARY KEY (id),
--     CONSTRAINT credentials_user_id_key UNIQUE (user_id)
-- );

-- CREATE TABLE IF NOT EXISTS public.roles
-- (
--     created_at timestamp(6) without time zone NOT NULL,
--     created_by bigint NOT NULL,
--     id bigint NOT NULL,
--     updated_at timestamp(6) without time zone NOT NULL,
--     updated_by bigint NOT NULL,
--     authorities character varying(255) COLLATE pg_catalog."default",
--     name character varying(255) COLLATE pg_catalog."default",
--     reference_id character varying(255) COLLATE pg_catalog."default",
--     CONSTRAINT roles_pkey PRIMARY KEY (id)
-- );

-- CREATE TABLE IF NOT EXISTS public.test_table
-- (
--     id bigint NOT NULL,
--     name character varying(50) COLLATE pg_catalog."default" NOT NULL,
--     CONSTRAINT test_table_pkey PRIMARY KEY (id)
-- );

-- CREATE TABLE IF NOT EXISTS public.user_role
-- (
--     role_id bigint,
--     user_id bigint NOT NULL,
--     CONSTRAINT user_role_pkey PRIMARY KEY (user_id)
-- );

-- CREATE TABLE IF NOT EXISTS public.users
-- (
--     is_account_non_expired boolean NOT NULL,
--     is_account_non_locked boolean NOT NULL,
--     is_enabled boolean NOT NULL,
--     is_mfa_enabled boolean NOT NULL,
--     login_attempts integer,
--     created_at timestamp(6) without time zone NOT NULL,
--     created_by bigint NOT NULL,
--     id bigint NOT NULL,
--     last_login_at timestamp(6) without time zone,
--     updated_at timestamp(6) without time zone NOT NULL,
--     updated_by bigint NOT NULL,
--     bio character varying(255) COLLATE pg_catalog."default",
--     email character varying(255) COLLATE pg_catalog."default",
--     first_name character varying(255) COLLATE pg_catalog."default",
--     last_name character varying(255) COLLATE pg_catalog."default",
--     phone_number character varying(255) COLLATE pg_catalog."default",
--     profile_image_url character varying(255) COLLATE pg_catalog."default",
--     qr_code_image_url character varying(255) COLLATE pg_catalog."default",
--     qr_code_secret_key text COLLATE pg_catalog."default",
--     reference_id character varying(255) COLLATE pg_catalog."default",
--     user_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
--     CONSTRAINT users_pkey PRIMARY KEY (id),
--     CONSTRAINT users_email_key UNIQUE (email),
--     CONSTRAINT users_user_id_key UNIQUE (user_id)
-- );

-- ALTER TABLE IF EXISTS public.confirmations
--     ADD CONSTRAINT fk2713gdbb1t0sl92kk97j5p0wt FOREIGN KEY (user_id)
--     REFERENCES public.users (id) MATCH SIMPLE
--     ON UPDATE NO ACTION
--     ON DELETE CASCADE;
-- CREATE INDEX IF NOT EXISTS confirmations_user_id_key
--     ON public.confirmations(user_id);


-- ALTER TABLE IF EXISTS public.credentials
--     ADD CONSTRAINT fkcbcgksvnqvqxrrc4dwv3qys65 FOREIGN KEY (user_id)
--     REFERENCES public.users (id) MATCH SIMPLE
--     ON UPDATE NO ACTION
--     ON DELETE CASCADE;
-- CREATE INDEX IF NOT EXISTS credentials_user_id_key
--     ON public.credentials(user_id);


-- ALTER TABLE IF EXISTS public.user_role
--     ADD CONSTRAINT fkj345gk1bovqvfame88rcx7yyx FOREIGN KEY (user_id)
--     REFERENCES public.users (id) MATCH SIMPLE
--     ON UPDATE NO ACTION
--     ON DELETE NO ACTION;
-- CREATE INDEX IF NOT EXISTS user_role_pkey
--     ON public.user_role(user_id);


-- ALTER TABLE IF EXISTS public.user_role
--     ADD CONSTRAINT fkt7e7djp752sqn6w22i6ocqy6q FOREIGN KEY (role_id)
--     REFERENCES public.roles (id) MATCH SIMPLE
--     ON UPDATE NO ACTION
--     ON DELETE NO ACTION;

-- END;


--  DATABASE DESIGN 

-- BEGIN

-- -- Create sequence
-- CREATE SEQUENCE IF NOT EXISTS primary_key_seq
--     START WITH 1
--     INCREMENT BY 1
--     NO MINVALUE
--     NO MAXVALUE
--     CACHE 1;

-- CREATE TABLE IF NOT EXISTS users (
--      id BIGINT NOT NULL DEFAULT nextval('primary_key_seq'),
--     user_id CHARACTER VARYING(255) NOT NULL UNIQUE,
--     first_name CHARACTER VARYING(255),
--     last_name CHARACTER VARYING(255),
--     email CHARACTER VARYING(255),
--     phone CHARACTER VARYING(255),
--     bio CHARACTER VARYING(255),
--     reference_id CHARACTER VARYING(255),
--     qr_code_secret CHARACTER VARYING(255),
--     qr_code_image_uri TEXT,
--     image_url CHARACTER VARYING(255),
--     last_login TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     login_attempts INTEGER DEFAULT 0,
--     mfa BOOLEAN NOT NULL DEFAULT FALSE,
--     enabled BOOLEAN NOT NULL DEFAULT FALSE,
--     account_non_expired BOOLEAN NOT NULL DEFAULT FALSE,
--     account_non_locked BOOLEAN NOT NULL DEFAULT FALSE,
--     created_by BIGINT NOT NULL,
--     updated_by BIGINT NOT NULL,
--     created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     CONSTRAINT uq_users_email UNIQUE (email),
--     CONSTRAINT uq_users_user_id UNIQUE (user_id),
--     CONSTRAINT fk_users_created_by FOREIGN KEY (created_by) REFERENCES users (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
--     CONSTRAINT fk_users_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
-- );

-- CREATE TABLE IF NOT EXISTS confirmations (
--     id SERIAL PRIMARY KEY,
--     key CHARACTER VARYING(255),
--     user_id BIGINT NOT NULL,
--     reference_id CHARACTER VARYING(255),
--     created_by BIGINT NOT NULL,
--     updated_by BIGINT NOT NULL,
--     created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     CONSTRAINT uq_confirmations_user_id UNIQUE (user_id),
--     CONSTRAINT uq_confirmations_key UNIQUE (key),
--     CONSTRAINT fk_confirmations_user_id FOREIGN KEY (user_id) REFERENCES users (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
--     CONSTRAINT fk_confirmations_created_by FOREIGN KEY (created_by) REFERENCES users (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE,
--     CONSTRAINT fk_confirmations_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE
-- );

-- CREATE TABLE IF NOT EXISTS documents (
--     id SERIAL PRIMARY KEY,
--     document_id CHARACTER VARYING(255) NOT NULL,
--     extension CHARACTER VARYING(10),
--     formatted_size CHARACTER VARYING(255),
--     icon CHARACTER VARYING(255),
--     name CHARACTER VARYING(255),
--     size BIGINT NOT NULL,
--     uri CHARACTER VARYING(255),
--     description CHARACTER VARYING(255),
--     reference_id CHARACTER VARYING(255),
--     created_by BIGINT NOT NULL,
--     updated_by BIGINT NOT NULL,
--     created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     CONSTRAINT uq_documents_document_id UNIQUE (document_id),
--     CONSTRAINT fk_documents_created_by FOREIGN KEY (created_by) REFERENCES users (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT,
--     CONSTRAINT fk_documents_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT
-- );

-- CREATE TABLE IF NOT EXISTS roles (
--     id SERIAL PRIMARY KEY,
--     authority CHARACTER VARYING(255),
--     name CHARACTER VARYING(255),
--     reference_id CHARACTER VARYING(255),
--     created_by BIGINT NOT NULL,
--     updated_by BIGINT NOT NULL,
--     created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     CONSTRAINT fk_roles_created_by FOREIGN KEY (created_by) REFERENCES users (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT,
--     CONSTRAINT fk_roles_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT
-- );

-- CREATE TABLE IF NOT EXISTS user_roles (
--     id SERIAL PRIMARY KEY,
--     user_id BIGINT NOT NULL,
--     role_id BIGINT NOT NULL,
--     CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT,
--     CONSTRAINT fk_user_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT
-- );

-- CREATE INDEX IF NOT EXISTS index_users_email ON users (email);
-- CREATE INDEX IF NOT EXISTS index_users_user_id ON users (user_id);
-- CREATE INDEX IF NOT EXISTS index_confirmations_user_id ON confirmations (user_id);
-- CREATE INDEX IF NOT EXISTS index_credentials_user_id ON credentials (user_id);
-- CREATE INDEX IF NOT EXISTS index_user_roles_user_id ON user_roles (user_id);

-- END;

-- ✅ No BEGIN...END – not valid in plain SQL scripts

-- ✅ Create sequence first
CREATE SEQUENCE IF NOT EXISTS primary_key_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- ✅ Step 1: Create users table WITHOUT self-referencing FKs
CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL DEFAULT nextval('primary_key_seq'),
    user_id CHARACTER VARYING(255) NOT NULL UNIQUE,
    first_name CHARACTER VARYING(255),
    last_name CHARACTER VARYING(255),
    email CHARACTER VARYING(255),
    phone CHARACTER VARYING(255),
    bio CHARACTER VARYING(255),
    reference_id CHARACTER VARYING(255),
    qr_code_secret CHARACTER VARYING(255),
    qr_code_image_uri TEXT,
    image_url CHARACTER VARYING(255),
    last_login TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    login_attempts INTEGER DEFAULT 0,
    mfa BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    account_non_expired BOOLEAN NOT NULL DEFAULT FALSE,
    account_non_locked BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_user_id UNIQUE (user_id)
);

-- ✅ Step 2: Add self-referencing FKs to users
ALTER TABLE users
    ADD CONSTRAINT fk_users_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE users
    ADD CONSTRAINT fk_users_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;

-- ✅ Step 3: Create other dependent tables

CREATE TABLE IF NOT EXISTS confirmations (
    id SERIAL PRIMARY KEY,
    key CHARACTER VARYING(255),
    user_id BIGINT NOT NULL,
    reference_id CHARACTER VARYING(255),
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_confirmations_user_id UNIQUE (user_id),
    CONSTRAINT uq_confirmations_key UNIQUE (key),
    CONSTRAINT fk_confirmations_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_confirmations_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_confirmations_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS documents (
    id SERIAL PRIMARY KEY,
    document_id CHARACTER VARYING(255) NOT NULL,
    extension CHARACTER VARYING(10),
    formatted_size CHARACTER VARYING(255),
    icon CHARACTER VARYING(255),
    name CHARACTER VARYING(255),
    size BIGINT NOT NULL,
    uri CHARACTER VARYING(255),
    description CHARACTER VARYING(255),
    reference_id CHARACTER VARYING(255),
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_documents_document_id UNIQUE (document_id),
    CONSTRAINT fk_documents_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_documents_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS roles (
    id SERIAL PRIMARY KEY,
    authority CHARACTER VARYING(255),
    name CHARACTER VARYING(255),
    reference_id CHARACTER VARYING(255),
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_roles_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_roles_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS user_roles (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT fk_user_roles_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_user_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS credentials (
    id SERIAL PRIMARY KEY,
    password CHARACTER VARYING(255) NOT NULL,
    user_id BIGINT NOT NULL,
    reference_id CHARACTER VARYING(255),
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_credentials_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_credentials_created_by FOREIGN KEY (created_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_credentials_updated_by FOREIGN KEY (updated_by) REFERENCES users (id) ON UPDATE CASCADE ON DELETE RESTRICT
);


-- ❗ Skipping index on non-existent credentials table
-- CREATE INDEX IF NOT EXISTS index_credentials_user_id ON credentials (user_id);

-- ✅ Create indexes
CREATE INDEX IF NOT EXISTS index_users_email ON users (email);
CREATE INDEX IF NOT EXISTS index_users_user_id ON users (user_id);
CREATE INDEX IF NOT EXISTS index_confirmations_user_id ON confirmations (user_id);
CREATE INDEX IF NOT EXISTS index_user_roles_user_id ON user_roles (user_id);
